import type { Locale } from '@/lib/types';

export const createEntryCopy = {
  ko: {
    backHome: '홈으로',
    title: '모험의 순간을 골라주세요.',
    intro: '스크린샷 한 장으로 시작해요. 인물 위치와 카드 비율은 편집기에서 조정할 수 있어요.',
    uploadTitle: '캐릭터 스크린샷을 추가하세요',
    uploadDescription: '사진을 고르면 바로 카드 편집을 시작할 수 있어요.',
    photoReadyTitle: '사진을 준비했어요',
    photoReadyDescription: '이제 이 장면을 모험가 카드로 완성할 수 있어요.',
    confirmUploadTitle: '저장된 카드의 사진을 바꿀까요?',
    dropIdle: '사진을 놓거나 파일을 선택하세요.',
    dropActive: '놓으면 사진을 준비합니다.',
    chooseFile: '사진 선택',
    chooseAnotherPhoto: '다른 사진 선택',
    fileTypes: 'JPG · PNG · WebP · 최대 24MB',
    privacy: '사진은 이 브라우저에서만 처리됩니다.',
    processing: '사진을 준비하고 있어요…',
    prepared: '사진을 준비했어요. 저장된 카드의 사진을 바꾸려면 확인해 주세요.',
    success: '사진을 추가했어요. 미리보기를 확인하고 편집을 계속하세요.',
    fileSelected: '선택한 사진',
    photoTipsTitle: '사진을 고를 때',
    photoTipFocus: '얼굴과 직업 장비가 잘 보이는 순간을 골라보세요.',
    photoTipLight: '밝은 장면과 어두운 장면 모두 카드에서 확인할 수 있어요.',
    cancelUpload: '업로드 취소',
    continueToEditor: '편집 계속하기',
    sampleTitle: '샘플로 편집을 먼저 둘러보기',
    sampleDescription: '내 사진 없이도 흐름을 살펴볼 수 있어요.',
    portraitSample: '인물 사진',
    landscapeSample: '동료와 함께',
    sampleAction: '이 예시로 시작',
    previewLabel: '카드 미리보기',
    samplePreviewLabel: '선택한 샘플 사진',
    confirmLabel: '예시 사진으로 현재 카드 바꾸기',
    confirmMessage: '이 브라우저에 저장된 카드를 선택한 예시로 바꿉니다.',
    confirmReplace: '예시 카드로 바꾸기',
    confirmUploadLabel: '저장된 카드의 사진 바꾸기',
    confirmUploadMessage: '이 브라우저에 저장된 카드의 사진을 새 사진으로 바꿉니다. 이름과 캐릭터 정보는 유지됩니다.',
    confirmUploadAction: '사진 바꾸기',
    cancelReplace: '저장된 카드 유지',
    resumeDraft: '저장된 카드 이어서 편집',
    cinematic: '시네마틱',
    editorial: '에디토리얼',
    identity: '모험가 기록',
    templatesLink: '카드 스타일 보기',
  },
  en: {
    backHome: 'Home',
    title: 'Choose a moment from your adventures.',
    intro: 'Start with one screenshot. Adjust its framing and card ratio in the editor.',
    uploadTitle: 'Add a character screenshot',
    uploadDescription: 'Choose a photo to move straight into card editing.',
    photoReadyTitle: 'Photo ready',
    photoReadyDescription: 'This moment is ready to become your adventurer card.',
    confirmUploadTitle: 'Replace the saved card photo?',
    dropIdle: 'Drop a photo here, or choose a file.',
    dropActive: 'Release to prepare your photo.',
    chooseFile: 'Choose a photo',
    chooseAnotherPhoto: 'Choose a different photo',
    fileTypes: 'JPG · PNG · WebP · up to 24 MB',
    privacy: 'Your photo stays in this browser.',
    processing: 'Preparing your photo…',
    prepared: 'Your photo is ready. Confirm before replacing the saved card photo.',
    success: 'Photo added. Check the preview, then continue editing.',
    fileSelected: 'Selected photo',
    photoTipsTitle: 'A note for choosing a screenshot',
    photoTipFocus: 'Choose a moment where your character and job gear are clear.',
    photoTipLight: 'Both bright and dark scenes can be checked on the card.',
    cancelUpload: 'Cancel upload',
    continueToEditor: 'Continue editing',
    sampleTitle: 'Try the editor with a sample',
    sampleDescription: 'Preview the editing flow without choosing a photo.',
    portraitSample: 'Character portrait',
    landscapeSample: 'With companions',
    sampleAction: 'Start with this sample',
    previewLabel: 'Card preview',
    samplePreviewLabel: 'Selected sample photo',
    confirmLabel: 'Replace the current card with an example',
    confirmMessage: 'This replaces the card saved in this browser with the selected example.',
    confirmReplace: 'Replace with example',
    confirmUploadLabel: 'Replace the photo in the saved card',
    confirmUploadMessage: 'This replaces the photo in the card saved in this browser. Your character details will stay.',
    confirmUploadAction: 'Replace photo',
    cancelReplace: 'Keep my saved card',
    resumeDraft: 'Continue editing saved card',
    cinematic: 'Cinematic',
    editorial: 'Editorial',
    identity: 'Adventurer Record',
    templatesLink: 'See card styles',
  },
  ja: {
    backHome: 'ホーム',
    title: '冒険の瞬間を選びましょう。',
    intro: 'スクリーンショット1枚から始めます。構図と比率は編集画面で調整できます。',
    uploadTitle: 'キャラクターの写真を追加',
    uploadDescription: '写真を選ぶとすぐにカード編集を始められます。',
    photoReadyTitle: '写真の準備ができました',
    photoReadyDescription: 'この場面を冒険者カードに仕上げられます。',
    confirmUploadTitle: '保存したカードの写真を置き換えますか？',
    dropIdle: 'ここに写真をドロップするか、ファイルを選択してください。',
    dropActive: 'ドロップすると写真を準備します。',
    chooseFile: '写真を選択',
    chooseAnotherPhoto: '別の写真を選択',
    fileTypes: 'JPG · PNG · WebP · 24MBまで',
    privacy: '写真はこのブラウザー内で処理します。',
    processing: '写真を準備しています…',
    prepared: '写真を準備しました。保存したカードの写真を置き換える前に確認してください。',
    success: '写真を追加しました。プレビューを確認して編集を続けてください。',
    fileSelected: '選択した写真',
    photoTipsTitle: '写真を選ぶとき',
    photoTipFocus: 'キャラクターとジョブ装備がよく見える場面を選びましょう。',
    photoTipLight: '明るい場面も暗い場面もカードで確認できます。',
    cancelUpload: 'アップロードをキャンセル',
    continueToEditor: '編集を続ける',
    sampleTitle: 'サンプルで編集を試す',
    sampleDescription: '写真を選ばずに編集の流れを確認できます。',
    portraitSample: 'キャラクター写真',
    landscapeSample: '仲間と一緒に',
    sampleAction: 'このサンプルで始める',
    previewLabel: 'カードプレビュー',
    samplePreviewLabel: '選択したサンプル写真',
    confirmLabel: '現在のカードをサンプルに置き換える',
    confirmMessage: 'このブラウザーに保存したカードを選んだサンプルに置き換えます。',
    confirmReplace: 'サンプルに置き換える',
    confirmUploadLabel: '保存したカードの写真を置き換える',
    confirmUploadMessage: '保存したカードの写真を新しい写真に置き換えます。キャラクター情報は保たれます。',
    confirmUploadAction: '写真を置き換える',
    cancelReplace: '保存したカードを保つ',
    resumeDraft: '保存したカードの編集を続ける',
    cinematic: 'シネマティック',
    editorial: 'エディトリアル',
    identity: '冒険者の記録',
    templatesLink: 'カードスタイルを見る',
  },
} satisfies Record<Locale, Record<string, string>>;
