import type { Locale } from '@/lib/types';

export const createEntryCopy = {
  ko: {
    eyebrow: '모험가 카드 만들기',
    titleStart: '모험의 한 장면을',
    titleEnd: '오래 간직하세요.',
    intro: '예시로 빠르게 시작하거나, 내 스크린샷을 골라 편집을 이어가세요.',
    pathsLabel: '카드 시작 방법',
    sampleTitle: '예시 카드로 시작',
    sampleDescription: 'Coner의 실제 샘플과 시네마틱 마스터를 편집기에서 열어요.',
    sampleAction: '예시로 시작하기',
    confirmLabel: '예시 카드로 현재 카드 바꾸기',
    confirmMessage: '이 브라우저에 저장된 카드가 예시 카드로 바뀝니다.',
    confirmReplace: '예시 카드로 바꾸기',
    cancelReplace: '저장된 카드 유지',
    resumeDraft: '저장된 카드 이어서 편집',
    or: '또는',
    uploadTitle: '내 스크린샷 사용',
    uploadDescription: 'JPG, PNG, WebP · 최대 24MB',
    dropIdle: '스크린샷을 여기에 놓으세요',
    dropActive: '놓으면 스크린샷을 준비합니다',
    chooseFile: '스크린샷 선택',
    fileTypes: 'JPG · PNG · WebP',
    privacy: '이미지는 이 기기에서 처리하고 브라우저에 저장합니다.',
    processing: '이미지를 준비하고 있어요…',
    success: '스크린샷을 추가했어요. 편집기에서 계속할 수 있어요.',
    continueToEditor: '편집기에서 계속하기',
    templatesLink: '템플릿 둘러보기',
    previewLabel: '실제 카드 미리보기',
    cardDescription: '모험가 카드',
    cinematic: '시네마틱',
    editorial: '에디토리얼',
    identity: '어드벤처러 ID',
    masterPrefix: '마스터',
  },
  en: {
    eyebrow: 'Create an adventurer card',
    titleStart: 'Keep a moment',
    titleEnd: 'from your adventure.',
    intro: 'Start with the sample, or bring in a screenshot and continue in the editor.',
    pathsLabel: 'Choose how to begin',
    sampleTitle: 'Start with the sample',
    sampleDescription: 'Open Coner and the Cinematic master in the editor, ready to make your own.',
    sampleAction: 'Open the sample',
    confirmLabel: 'Replace the current card with the sample',
    confirmMessage: 'This replaces the card saved in this browser with the sample.',
    confirmReplace: 'Replace with sample',
    cancelReplace: 'Keep my saved card',
    resumeDraft: 'Continue editing my saved card',
    or: 'or',
    uploadTitle: 'Use your screenshot',
    uploadDescription: 'JPG, PNG, or WebP · up to 24 MB',
    dropIdle: 'Drop a screenshot here',
    dropActive: 'Release to prepare your screenshot',
    chooseFile: 'Choose screenshot',
    fileTypes: 'JPG · PNG · WebP',
    privacy: 'Your image is prepared on this device and saved in this browser.',
    processing: 'Preparing your image…',
    success: 'Screenshot added. Continue when you are ready.',
    continueToEditor: 'Continue in the editor',
    templatesLink: 'Explore the templates',
    previewLabel: 'A real card preview',
    cardDescription: 'adventurer card',
    cinematic: 'Cinematic',
    editorial: 'Editorial',
    identity: 'Adventurer ID',
    masterPrefix: 'Master',
  },
  ja: {
    eyebrow: '冒険者カードをつくる',
    titleStart: '冒険のひとコマを',
    titleEnd: 'カードに残そう。',
    intro: 'サンプルから始めるか、スクリーンショットを選んで編集を続けましょう。',
    pathsLabel: 'カードの作成方法',
    sampleTitle: 'サンプルから始める',
    sampleDescription: 'Conerの実際のサンプルとシネマティックマスターを編集画面で開きます。',
    sampleAction: 'サンプルを開く',
    confirmLabel: '現在のカードをサンプルに置き換える',
    confirmMessage: 'このブラウザーに保存したカードをサンプルで置き換えます。',
    confirmReplace: 'サンプルに置き換える',
    cancelReplace: '保存したカードを保つ',
    resumeDraft: '保存したカードの編集を続ける',
    or: 'または',
    uploadTitle: 'スクリーンショットを使う',
    uploadDescription: 'JPG、PNG、WebP · 24MB以下',
    dropIdle: 'ここにスクリーンショットをドロップ',
    dropActive: 'ドロップすると画像を準備します',
    chooseFile: '画像を選択',
    fileTypes: 'JPG · PNG · WebP',
    privacy: '画像はこの端末で処理し、ブラウザーに保存します。',
    processing: '画像を準備しています…',
    success: '画像を追加しました。準備ができたら編集画面へ進めます。',
    continueToEditor: '編集画面で続ける',
    templatesLink: 'テンプレートを見る',
    previewLabel: '実際のカードプレビュー',
    cardDescription: '冒険者カード',
    cinematic: 'シネマティック',
    editorial: 'エディトリアル',
    identity: 'アドベンチャラー ID',
    masterPrefix: 'マスター',
  },
} satisfies Record<Locale, Record<string, string>>;
