import { readFile, writeFile } from 'node:fs/promises';
const root='docs/qa/phase302-jobmark-correction/';
const plans=['job-matrix','retained-name-alternatives','family-strength','fankit-size-sweep','e2-placement'];
const cards=[];
for(const name of plans){
  const plan=JSON.parse(await readFile(root+`qa-cases-${name}.json`,'utf8'));
  for(const item of plan.cases){
    const report=JSON.parse(await readFile(root+`raw/${item.id}.json`,'utf8'));
    if(!report.previewScreenshot?.path)throw new Error('Preview missing: '+item.id);
    cards.push({id:item.id,group:name,master:item.master,job:item.jobId,mark:item.jobMark.variant,font:item.fontSet,
      strength:report.apiResult?.jobMark?.familyStrength,size:report.apiResult?.jobMark?.primarySizeLogicalPx,
      image:report.previewScreenshot.path,exports:(report.exports??[]).map(x=>({format:x.format,path:x.path})),
      source:report.jobSourceEvidence?.actualResolvedSource??item.sourceTier,
      pass:report.pass});
  }
}
const payload=JSON.stringify(cards).replaceAll('<','\\u003c');
const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phase 3.0.2 · Full emblem</title>
<style>:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#121512;color:#eee8da}*{box-sizing:border-box}body{margin:0}header{padding:24px;max-width:1900px;margin:auto}h1{font-size:25px;margin:8px 0}p{color:#bfc6bb;line-height:1.6;max-width:940px}nav{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}button,select,a{font:inherit;color:inherit}button,select{padding:9px 12px;border:1px solid #596050;background:#242b23;border-radius:3px}button{cursor:pointer}button[aria-pressed=true]{background:#d9cbb0;color:#172016}select{max-width:100%}.filters{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px;max-width:1900px;padding:0 24px 36px;margin:auto}figure{margin:0;background:#1b201a;border:1px solid #3d4539}figcaption{padding:14px;line-height:1.6;font-size:14px;min-height:104px}figcaption strong{font-size:17px}img{display:block;width:100%;height:auto}.links{display:flex;gap:12px;flex-wrap:wrap}.links a{text-underline-offset:4px}footer{padding:0 24px 28px;max-width:1900px;margin:auto;color:#c4c9bf}.cards.single{grid-template-columns:minmax(0,1080px);justify-content:center}@media(max-width:1000px){.cards{grid-template-columns:1fr;max-width:800px;gap:28px}header{padding:20px}.cards{padding:0 16px 24px}h1{font-size:23px}}</style>
<header><small>PHASE 3.0.2 · EXPLORATION</small><h1>전체 Job 문양 · 실제 카드 비교</h1><p>카드를 크게 보며 A/B/C와 밀도·크기를 비교하세요. 정보 텍스트는 공통 Serif와 같은 크기이며, 이름과 Editorial RDM은 display 역할을 유지합니다. 최종 production 후보는 아직 선택하지 않았습니다.</p><nav aria-label="비교 모드"></nav><div class="filters"><select id="master" aria-label="Master"><option value="cinematic">C2 · Cinematic</option><option value="editorial">E2 · Editorial</option><option value="id-card">I3 · Identity</option></select><select id="job" aria-label="Job"></select><button id="single" aria-pressed="false">한 장씩 크게 보기</button><a href="11-all-master-comparison.png">전체 A/B/C 보드</a></div><p id="status" aria-live="polite"></p></header><main class="cards"></main><footer><a href="REPORT.md">결과 보고서</a> · <a href="USER-COMMENTS.md">7개 수정 코멘트</a> · <a href="16-fankit-size-sweep.png">Fan Kit 크기 측정</a></footer>
<script>const cards=${payload};const modes=[['job-matrix','A / B / C'],['retained-name-alternatives','기존 Serif 이름 후보'],['family-strength','아이콘 밀도'],['fankit-size-sweep','Fan Kit 크기'],['e2-placement','E2 위치']];const names={cinematic:'C2',editorial:'E2','id-card':'I3'};const jobs={'red-mage':'RDM · Red Mage',dragoon:'DRG · Dragoon',gunbreaker:'GNB · Gunbreaker','white-mage':'WHM · White Mage','black-mage':'BLM · Black Mage',astrologian:'AST · Fan Kit',reaper:'RPR · HQ raster',beastmaster:'BST · Generic'};let mode='job-matrix';const main=document.querySelector('main'),master=document.querySelector('#master'),job=document.querySelector('#job'),nav=document.querySelector('nav');Object.entries(jobs).forEach(([id,label])=>job.add(new Option(label,id)));function render(){let rows=cards.filter(x=>x.group===mode);if(mode==='job-matrix')rows=rows.filter(x=>x.master===master.value&&x.job===job.value);else if(mode==='family-strength'||mode==='retained-name-alternatives')rows=rows.filter(x=>x.master===master.value);master.disabled=mode==='fankit-size-sweep'||mode==='e2-placement';job.disabled=mode!=='job-matrix';main.replaceChildren();rows.forEach(x=>{const figure=document.createElement('figure'),caption=document.createElement('figcaption'),title=document.createElement('strong');title.textContent=names[x.master]+' · '+x.font+' · '+x.mark+' · '+(jobs[x.job]??x.job);caption.append(title,document.createElement('br'));const details=document.createElement('span');details.textContent=(x.strength!=null?'Strength '+Math.round(x.strength*100)+'% · ':'')+(x.size!=null?x.size+' logical px · ':'')+x.source;caption.append(details);const links=document.createElement('div');links.className='links';[{format:'Preview',path:x.image},...x.exports].forEach(e=>{const a=document.createElement('a');a.textContent=e.format.toUpperCase();a.href=e.path;a.target='_blank';links.append(a)});caption.append(links);const a=document.createElement('a');a.href=x.image;a.target='_blank';const img=document.createElement('img');img.src=x.image;img.alt=title.textContent;img.loading='lazy';a.append(img);figure.append(caption,a);main.append(figure)});document.querySelector('#status').textContent=rows.length+'개 실제 카드 · 1080×1350 Preview';nav.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)))}modes.forEach(([id,label])=>{const b=document.createElement('button');b.dataset.mode=id;b.textContent=label;b.onclick=()=>{mode=id;render()};nav.append(b)});master.onchange=job.onchange=render;document.querySelector('#single').onclick=e=>{const active=main.classList.toggle('single');e.currentTarget.setAttribute('aria-pressed',String(active))};render();</script></html>`;
await writeFile(root+'comparison.html',html);
console.log(JSON.stringify({viewer:root+'comparison.html',cards:cards.length,responsiveSingleColumnBelow:1000}));
